export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN'
export const LOAD_USER = 'LOAD_USER'

export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const SET_EDITING_PRODUCT = 'SET_EDITING_PRODUCT'
